### ISSUE TITLE
!mymt не находит юзера, если ник в дисе не совпадает с ником в игре.

### ISSUE THREAD

**Issue by bit1creative** [Horodep/mamanda-issues-tracker#4]
1. Product and Version: GladGladd#0157 v1.0.0
2. Component: !mymt command.
3. Platform: All.
4. Operating Systems: All.
5. Environment: Discord v(Stable) 73806 .
6. Severity: S3 Major.
7. Priority: P2 Medium.
8. Status: New.
9. Assign to: Horodep.
10. Description: комманда !mymt не находит пользователя если его ник в дискорде не совпадает с игровым. При это не выводится сообщение об ошибке.
    10.1 Steps to reproduce:
        - Ник в игре не должен совпадать с никнеймом в дискорде.
        - Перейти в канал где работают команды бота.
        - Ввести команду !mymt.
        - PROFIT.
    10.2 Expected result: бот кидает сообщение: "${ник игрока} : ${время в дискорде за последнюю неделю} / ${время в игре за последнюю неделю} = ${соотношение в процентах}"
    10.3 Actual result: ничего.
11. Attachments: [screenshot](https://ibb.co/bKS3WqP)

**Comment by Horodep** [comment]
fixed https://github.com/Horodep/mamanda/commit/1712fc610e4788b3916ad7fc9829479748b37c1f
